server:
  port: 8080
##  servlet:
##    context-path: /cc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fileshare?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource




#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classspath:mapper/*.xml
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
